package mldsa44

import (
	"bytes"

	"github.com/cloudflare/circl/sign/mldsa/mldsa44"

	cmtcrypto "github.com/cometbft/cometbft/crypto"
	cryptotypes "github.com/cosmos/cosmos-sdk/crypto/types"
)

const name = "mldsa44"

// PubKey is defined in keys.pb.go generated by protobuf.

var _ cryptotypes.PubKey = (*PubKey)(nil)

// String returns a string representation of the public key.
func (m *PubKey) String() string {
	return "PubKeyMldsa44{" + string(m.Bytes()) + "}"
}

// Bytes returns the raw bytes of the public key.
func (m *PubKey) Bytes() []byte {
	if m == nil {
		return nil
	}
	return m.Key
}

// Equals checks if two public keys are equal.
func (m *PubKey) Equals(other cryptotypes.PubKey) bool {
	pk2, ok := other.(*PubKey)
	if !ok {
		return false
	}
	return bytes.Equal(m.Key, pk2.Key)
}

// Address returns the address corresponding to the public key.
func (m *PubKey) Address() cmtcrypto.Address {
	return cmtcrypto.AddressHash(m.Bytes())
}

// Type returns the key type name.
func (m *PubKey) Type() string {
	return name
}

// VerifySignature verifies a signature for a message using the public key.
func (m *PubKey) VerifySignature(msg, sig []byte) bool {
	var pk mldsa44.PublicKey
	if err := pk.UnmarshalBinary(m.Key); err != nil {
		return false
	}
	return mldsa44.Verify(&pk, msg, sig, nil)
}
