package mldsa

import (
	"bytes"
	"log"

	"github.com/cloudflare/circl/sign/mldsa/mldsa44"

	cmtcrypto "github.com/cometbft/cometbft/crypto"
	cryptotypes "github.com/cosmos/cosmos-sdk/crypto/types"
)

const name = "mldsa44"

// PubKey is defined in keys.pb.go generated by protobuf.

var _ cryptotypes.PubKey = (*PubKey)(nil)

// String returns a string representation of the public key.
func (m *PubKey) String() string {
	return "PubKeyMldsa44{" + string(m.Bytes()) + "}"
}

// Bytes returns the raw bytes of the public key.
func (m *PubKey) Bytes() []byte {
	if m == nil {
		return nil
	}
	return m.Key
}

// Equals checks if two public keys are equal.
func (m *PubKey) Equals(other cryptotypes.PubKey) bool {
	pk2, ok := other.(*PubKey)
	if !ok {
		return false
	}
	return bytes.Equal(m.Key, pk2.Key)
}

// Address returns the address corresponding to the public key.
func (m *PubKey) Address() cmtcrypto.Address {
	log.Printf("MLDSA44 PubKey Address() called")

	if m == nil || m.Key == nil {
		log.Printf("MLDSA44 PubKey Address() ERROR: public key or Key field is nil")
		return nil
	}

	log.Printf("MLDSA44 PubKey Address() public key length: %d", len(m.Key))

	addr := cmtcrypto.AddressHash(m.Bytes())
	log.Printf("MLDSA44 PubKey Address() generated address: %x", addr)

	return addr
}

// Type returns the key type name.
func (m *PubKey) Type() string {
	return "tendermint/PubKeyMLDSA44"
}

// VerifySignature verifies a signature for a message using the public key.
func (m *PubKey) VerifySignature(msg, sig []byte) bool {
	log.Printf("MLDSA44 PubKey VerifySignature() called")

	if m == nil || m.Key == nil {
		log.Printf("MLDSA44 PubKey VerifySignature() ERROR: public key or Key field is nil")
		return false
	}

	var pk mldsa44.PublicKey
	// Use UnmarshalBinary() which expects the packed format from MarshalBinary()
	if err := pk.UnmarshalBinary(m.Key); err != nil {
		log.Printf("MLDSA44 PubKey VerifySignature() ERROR: failed to unmarshal public key: %v", err)
		return false
	}

	result := mldsa44.Verify(&pk, msg, sig, nil)
	log.Printf("MLDSA44 PubKey VerifySignature() result: %v", result)

	return result
}
